name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  ## What's Changed
  $CHANGES

change-template: '- $TITLE'
change-title-escapes: '\<*_&`#@'

sort-by: merged_at
sort-direction: ascending

categories:
  - title: '🚀 Features'
    when:
      conventional:
        type: 'feat'
  - title: '🐛 Bug Fixes'
    when:
      conventional:
        type: 'fix'
  - title: '🚜 Refactor'
    when:
      conventional:
        type: 'refactor'
  - title: '📚 Documentation'
    when:
      conventional:
        type: 'docs'
  - title: '⚡ Performance'
    when:
      conventional:
        type: 'perf'
  - title: '🎨 Styling'
    when:
      conventional:
        type: 'style'
  - title: '🧪 Testing'
    when:
      conventional:
        type: 'test'
  - title: '⚙️ Miscellaneous Tasks'
    when:
      conventional:
        types: ['chore', 'ci']
  - title: '💼 Other'